name: abg_utils
description: Utils for ABG projects
version: 8.0.8

homepage: https://www.abg-studio.com

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  #
  #  razorpay_flutter: ^1.2.7 # 20mb нет поддержки api 31
  razorpay_flutter_31: ^1.3.2
  flutter_stripe: ^9.5.0+1
  flutter_paystack: ^1.0.5+1
  http_auth: ^1.0.1
  #

  csv: ^6.0.0
  qr_flutter: ^4.0.0
  pdf: ^3.6.4

  cloud_firestore: ^4.14.0
  firebase_core: ^2.0.0
  firebase_auth: ^4.4.0
  firebase_messaging: ^14.0.0
  firebase_storage: ^11.1.0

  flutter_app_badger: ^1.3.0

  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^5.0.11
  google_sign_in_web: ^0.12.0+4
  google_maps_webservice: ^0.0.20-nullsafety.5

  connectivity_plus: ^5.0.2
  device_info_plus: ^4.0.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.1.0
  matrix4_transform: ^2.0.1
  flutter_html: ^2.2.1
  js: ^0.6.3
  timeago: ^3.1.0
  universal_html: ^2.0.8
  geolocator: ^11.1.0
  uuid: ^4.1.0
  google_maps_flutter: ^2.0.3
  maps_toolkit: ^2.0.0
  path_provider: ^2.0.8
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.18
  archive: ^3.1.6
  http: ^0.13.4
  webview_flutter: ^2.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0

flutter:
  assets: # использовать так Image.asset("assets/noimage.png", package: 'abg_utils', fit: BoxFit.contain,)
    - assets/
    - assets/noimage.png
    - assets/elements/
